# Change these first
owner: Adding-Technology # Your GitHub organization or username, where this repository lives
repo: falles.app.api.upptime # The name of this repository

sites:
  - name: Landing page
    url: https://falles.app
    icon: https://falles.app/favicon.png
  - name: API
    url: https://api.falles.app/health
    icon: https://falles.app/favicon.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.falles.app
  # baseUrl: /your-repo-name
  logoUrl: https://falles.app/favicon.png
  name: Monitor de estado falles.app
  introTitle: "**falles.app** es tu aplicación de gestión de asociaciones falleras"
  introMessage: Esta página muestra el estado de los diferentes servicios que conforman falles.app
  navbar:
    - title: Estado
      href: /
    - title: GitHub Monitor
      href: https://github.com/Adding-Technology/falles.app.api.upptime
    - title: GitHub falles.app
      href: https://github.com/Adding-Technology/falles.app.api

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
